export const images = [
    {
        src:'https://images.freeimages.com/images/large-previews/ad2/sky-colours-1197564.jpg',
        alt:'picOne'
    },
    {
        src:'https://images.freeimages.com/images/large-previews/b23/sunset-1-1404015.jpg',
        alt:'picTwo'
    },
    {
        src:'https://images.freeimages.com/images/large-previews/159/offshore-sunset-10-1398250.jpg',
        alt:'picThree'
    },
    {
        src:'https://images.freeimages.com/images/large-previews/499/wind-and-energy-1622460.jpg',
        alt:'picThree'
    },
    {
        src:'https://images.freeimages.com/images/large-previews/b96/new-and-old-energy-1309286.jpg',
        alt:'picThree'
    }
]